
## Themes
theme: jekyll-theme-minimal
title: O3 Aerial Solutions
description: Charlotte's Premier sUAS Company
logo: https://media-exp1.licdn.com/dms/image/C5603AQEjpWRtfGTu9Q/profile-displayphoto-shrink_800_800/0/1593112650172?e=1626307200&v=beta&t=_8iQKxnbGrZ3UbyAC1tOFfIV193I99dadgJh3pVN9DA
show_downloads: false
## Change URLs
github:
  repository_url: site.github.repository_nwo
  another_url: www.google.com
